// Code generated by ChatGPT

/**
 * Format a post's creation time to a human-readable format.
 *
 * Examples:
 *  - Less than a minute ago: "Just now"
 *  - 1 minute ago: "1m"
 *  - 1 hour ago: "1h"
 *  - 1 day ago: "1d"
 *  - More than 1 day ago: "MMM D" (e.g. "Jan 24")
 *
 * @param {string} createdAt - The post's creation time as a string
 * @returns {string} The formatted date
 */
export const formatPostDate = (createdAt) => {
  const currentDate = new Date();
  const createdAtDate = new Date(createdAt);

  const timeDifferenceInSeconds = Math.floor(
    (currentDate - createdAtDate) / 1000
  );
  const timeDifferenceInMinutes = Math.floor(timeDifferenceInSeconds / 60);
  const timeDifferenceInHours = Math.floor(timeDifferenceInMinutes / 60);
  const timeDifferenceInDays = Math.floor(timeDifferenceInHours / 24);

  if (timeDifferenceInDays > 1) {
    return createdAtDate.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
  } else if (timeDifferenceInDays === 1) {
    return "1d";
  } else if (timeDifferenceInHours >= 1) {
    return `${timeDifferenceInHours}h`;
  } else if (timeDifferenceInMinutes >= 1) {
    return `${timeDifferenceInMinutes}m`;
  } else {
    return "Just now";
  }
};

/**
 * Format a user's join date to a human-readable format.
 *
 * @param {string} createdAt - The user's join date as a string
 * @returns {string} The formatted date
 */
export const formatMemberSinceDate = (createdAt) => {
  const date = new Date(createdAt);
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const month = months[date.getMonth()];
  const year = date.getFullYear();
  return `Joined ${month} ${year}`;
};
